version: '3'

services:
  backend:
    build:
      context: ./django
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./react/blogapi
    volumes:
      - react_build:/react/build
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:8080
    volumes:
      - react_build:/var/www/react
    depends_on:
      - backend
      - frontend
volumes:
  react_build:
