apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: backend
  name: backend
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: backend
status:
  loadBalancer: {}
